name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_REGION: 'us-east-1'
  AWS_S3_BUCKET: 'my-bucket-node'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag community:latest
    - name: Run docker container
      run: docker run -d -p 80:80 --name community community:latest
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy static site to S3 bucket
      run: |
        mkdir build
        docker cp community:/usr/share/nginx/html ./build
        docker stop community
        aws s3 sync ./build s3://${{ env.AWS_S3_BUCKET }} --delete
